stages:
  - test

image: python:3.14

variables:
  APP_ENV: test
  DATABASE_URL: postgresql+psycopg://todo_user:123456@postgres:5432/todo_db_test
  POSTGRES_DB: todo_db_test
  POSTGRES_USER: todo_user
  POSTGRES_PASSWORD: 123456
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test:
  stage: test

  services:
    - name: postgres:17
      alias: postgres

  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install -r requirements.txt

  script:
    - alembic upgrade head
    - pytest -v
