apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque

stringData:
  database: {{ .Values.database.name | quote }}
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
