apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: alloy
  namespace: observability

spec:
  selector:
    matchLabels:
      app: alloy

  template:
    metadata:
      labels:
        app: alloy

    spec:
      serviceAccountName: alloy

      containers:
        - name: alloy
          image: grafana/alloy:latest

          args:
            - run
            - /etc/alloy/config.alloy

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          volumeMounts:
            - name: config
              mountPath: /etc/alloy

      volumes:
        - name: config
          configMap:
            name: alloy-config
