replicaCount: 3

image:
  repository: ghcr.io/estrangegit/todo-app-backend
  tag: ""
  pullPolicy: IfNotPresent

container:
  port: 8000

service:
  port: 8000

config:
  debug: true

  jwt:
    accessTokenExpireMinutes: 30

secrets:
  databaseUrl: "postgresql+psycopg://todo_user:123456@postgres:5432/todo_db"
  jwtSecretKey: "change-me-in-production"
