apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  JWT_SECRET_KEY:  {{ .Values.secrets.jwtSecretKey | quote }}
