apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config

data:
  PROJECT_NAME: Todo API
  PROJECT_VERSION: "0.1.0"
  DEBUG: "true"

  JWT_ALGORITHM: HS256
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
