name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v7

      - name: Show kubectl version
        run: kubectl version

      - name: Show nodes
        run: kubectl get nodes
